// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPjC_iuhFHQLzugziGstC8WPKORXXDtlQ',
    appId: '1:862447107769:web:45135f3e2bfbb39c556568',
    messagingSenderId: '862447107769',
    projectId: 'blindspot-authentication',
    authDomain: 'blindspot-authentication.firebaseapp.com',
    storageBucket: 'blindspot-authentication.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmoTaNmMYRTqo1g4eu0pSW09wdzO1NEXE',
    appId: '1:862447107769:android:58ea72e4b6a2a4a8556568',
    messagingSenderId: '862447107769',
    projectId: 'blindspot-authentication',
    storageBucket: 'blindspot-authentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFFP8oCMi8V4ofJVPpQAu4lE5E9HBP8xk',
    appId: '1:862447107769:ios:1a58085374555d43556568',
    messagingSenderId: '862447107769',
    projectId: 'blindspot-authentication',
    storageBucket: 'blindspot-authentication.appspot.com',
    iosClientId: '862447107769-jpjqjbddg9c357bmd0d5sa80qg05fe28.apps.googleusercontent.com',
    iosBundleId: 'com.example.blindspotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFFP8oCMi8V4ofJVPpQAu4lE5E9HBP8xk',
    appId: '1:862447107769:ios:1a58085374555d43556568',
    messagingSenderId: '862447107769',
    projectId: 'blindspot-authentication',
    storageBucket: 'blindspot-authentication.appspot.com',
    iosClientId: '862447107769-jpjqjbddg9c357bmd0d5sa80qg05fe28.apps.googleusercontent.com',
    iosBundleId: 'com.example.blindspotApp',
  );
}
