// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUe5SFEv-mMRiUKtYFlz_3a0gAkjw5m4g',
    appId: '1:687784936826:web:5ff897ab51e32c019442c3',
    messagingSenderId: '687784936826',
    projectId: 'cs5520-sailorsenshi-blindspot',
    authDomain: 'cs5520-sailorsenshi-blindspot.firebaseapp.com',
    databaseURL: 'https://cs5520-sailorsenshi-blindspot-default-rtdb.firebaseio.com',
    storageBucket: 'cs5520-sailorsenshi-blindspot.appspot.com',
    measurementId: 'G-K16SE49L8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAutg2MTh0dxvX4Cg63S1rfjNyq98iVGoY',
    appId: '1:687784936826:android:fcd4a683c597d2c19442c3',
    messagingSenderId: '687784936826',
    projectId: 'cs5520-sailorsenshi-blindspot',
    databaseURL: 'https://cs5520-sailorsenshi-blindspot-default-rtdb.firebaseio.com',
    storageBucket: 'cs5520-sailorsenshi-blindspot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYaL6WyixGPx7xIkDM3I0SSb02_NwytZE',
    appId: '1:687784936826:ios:2430624afc807fd89442c3',
    messagingSenderId: '687784936826',
    projectId: 'cs5520-sailorsenshi-blindspot',
    databaseURL: 'https://cs5520-sailorsenshi-blindspot-default-rtdb.firebaseio.com',
    storageBucket: 'cs5520-sailorsenshi-blindspot.appspot.com',
    iosClientId: '687784936826-6osjraa55gjuqvdsh84nqijrhcvfpvmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.blindspotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYaL6WyixGPx7xIkDM3I0SSb02_NwytZE',
    appId: '1:687784936826:ios:2430624afc807fd89442c3',
    messagingSenderId: '687784936826',
    projectId: 'cs5520-sailorsenshi-blindspot',
    databaseURL: 'https://cs5520-sailorsenshi-blindspot-default-rtdb.firebaseio.com',
    storageBucket: 'cs5520-sailorsenshi-blindspot.appspot.com',
    iosClientId: '687784936826-6osjraa55gjuqvdsh84nqijrhcvfpvmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.blindspotApp',
  );
}
